/* amalgame.vala.c generated by valac 0.56.3, the Vala compiler
 * generated from amalgame.vala, do not modify */

/* amalgame.vala*/

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_LEXER (lexer_get_type ())
#define LEXER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LEXER, Lexer))
#define LEXER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LEXER, LexerClass))
#define IS_LEXER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LEXER))
#define IS_LEXER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LEXER))
#define LEXER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LEXER, LexerClass))

typedef struct _Lexer Lexer;
typedef struct _LexerClass LexerClass;

#define TYPE_PARSER (parser_get_type ())
#define PARSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PARSER, Parser))
#define PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PARSER, ParserClass))
#define IS_PARSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PARSER))
#define IS_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PARSER))
#define PARSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PARSER, ParserClass))

typedef struct _Parser Parser;
typedef struct _ParserClass ParserClass;

#define TYPE_AST_NODE (ast_node_get_type ())
#define AST_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_AST_NODE, AstNode))
#define AST_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_AST_NODE, AstNodeClass))
#define IS_AST_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_AST_NODE))
#define IS_AST_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_AST_NODE))
#define AST_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_AST_NODE, AstNodeClass))

typedef struct _AstNode AstNode;
typedef struct _AstNodeClass AstNodeClass;

#define TYPE_FUNCTION_NODE (function_node_get_type ())
#define FUNCTION_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FUNCTION_NODE, FunctionNode))
#define FUNCTION_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FUNCTION_NODE, FunctionNodeClass))
#define IS_FUNCTION_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FUNCTION_NODE))
#define IS_FUNCTION_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FUNCTION_NODE))
#define FUNCTION_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FUNCTION_NODE, FunctionNodeClass))

typedef struct _FunctionNode FunctionNode;
typedef struct _FunctionNodeClass FunctionNodeClass;
#define _ast_node_unref0(var) ((var == NULL) ? NULL : (var = (ast_node_unref (var), NULL)))
#define _parser_unref0(var) ((var == NULL) ? NULL : (var = (parser_unref (var), NULL)))
#define _lexer_unref0(var) ((var == NULL) ? NULL : (var = (lexer_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

static gint _vala_main (gchar** args,
                 gint args_length1);
VALA_EXTERN gchar* read_file_contents (const gchar* path);
VALA_EXTERN gpointer lexer_ref (gpointer instance);
VALA_EXTERN void lexer_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_lexer (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags);
VALA_EXTERN void value_set_lexer (GValue* value,
                      gpointer v_object);
VALA_EXTERN void value_take_lexer (GValue* value,
                       gpointer v_object);
VALA_EXTERN gpointer value_get_lexer (const GValue* value);
VALA_EXTERN GType lexer_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Lexer, lexer_unref)
VALA_EXTERN Lexer* lexer_new (const gchar* source);
VALA_EXTERN Lexer* lexer_construct (GType object_type,
                        const gchar* source);
VALA_EXTERN gpointer parser_ref (gpointer instance);
VALA_EXTERN void parser_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_parser (const gchar* name,
                               const gchar* nick,
                               const gchar* blurb,
                               GType object_type,
                               GParamFlags flags);
VALA_EXTERN void value_set_parser (GValue* value,
                       gpointer v_object);
VALA_EXTERN void value_take_parser (GValue* value,
                        gpointer v_object);
VALA_EXTERN gpointer value_get_parser (const GValue* value);
VALA_EXTERN GType parser_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Parser, parser_unref)
VALA_EXTERN Parser* parser_new (Lexer* lexer);
VALA_EXTERN Parser* parser_construct (GType object_type,
                          Lexer* lexer);
VALA_EXTERN gpointer ast_node_ref (gpointer instance);
VALA_EXTERN void ast_node_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_ast_node (const gchar* name,
                                 const gchar* nick,
                                 const gchar* blurb,
                                 GType object_type,
                                 GParamFlags flags);
VALA_EXTERN void value_set_ast_node (GValue* value,
                         gpointer v_object);
VALA_EXTERN void value_take_ast_node (GValue* value,
                          gpointer v_object);
VALA_EXTERN gpointer value_get_ast_node (const GValue* value);
VALA_EXTERN GType ast_node_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AstNode, ast_node_unref)
VALA_EXTERN GType function_node_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FunctionNode, ast_node_unref)
VALA_EXTERN FunctionNode* parser_parse_function (Parser* self);
VALA_EXTERN void ast_node_print (AstNode* self,
                     gint indent);

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	gchar* source_code = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	Lexer* lexer = NULL;
	const gchar* _tmp2_;
	Lexer* _tmp3_;
	Parser* parser = NULL;
	Lexer* _tmp4_;
	Parser* _tmp5_;
	FunctionNode* fn = NULL;
	Parser* _tmp6_;
	FunctionNode* _tmp7_;
	FunctionNode* _tmp8_;
	gint result;
	if (args_length1 < 2) {
		g_print ("Usage: amalgame <source.amal>\n");
		result = 1;
		return result;
	}
	_tmp0_ = args[1];
	_tmp1_ = read_file_contents (_tmp0_);
	source_code = _tmp1_;
	_tmp2_ = source_code;
	_tmp3_ = lexer_new (_tmp2_);
	lexer = _tmp3_;
	_tmp4_ = lexer;
	_tmp5_ = parser_new (_tmp4_);
	parser = _tmp5_;
	_tmp6_ = parser;
	_tmp7_ = parser_parse_function (_tmp6_);
	fn = _tmp7_;
	_tmp8_ = fn;
	ast_node_print ((AstNode*) _tmp8_, 0);
	result = 0;
	_ast_node_unref0 (fn);
	_parser_unref0 (parser);
	_lexer_unref0 (lexer);
	_g_free0 (source_code);
	return result;
}

int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}

