/* lexer.vala.c generated by valac 0.56.3, the Vala compiler
 * generated from lexer.vala, do not modify */

/* lexer.vala*/

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_LEXER (lexer_get_type ())
#define LEXER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LEXER, Lexer))
#define LEXER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LEXER, LexerClass))
#define IS_LEXER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LEXER))
#define IS_LEXER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LEXER))
#define LEXER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LEXER, LexerClass))

typedef struct _Lexer Lexer;
typedef struct _LexerClass LexerClass;
typedef struct _LexerPrivate LexerPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_TOKEN (token_get_type ())
#define TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TOKEN, Token))
#define TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TOKEN, TokenClass))
#define IS_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TOKEN))
#define IS_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TOKEN))
#define TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TOKEN, TokenClass))

typedef struct _Token Token;
typedef struct _TokenClass TokenClass;
typedef enum  {
	TOKEN_TYPE_IDENTIFIER,
	TOKEN_TYPE_KEYWORD,
	TOKEN_TYPE_NUMBER,
	TOKEN_TYPE_STRING,
	TOKEN_TYPE_SYMBOL,
	TOKEN_TYPE_END_OF_FILE,
	TOKEN_TYPE_UNKNOWN
} TokenType;

#define TYPE_TOKEN_TYPE (token_type_get_type ())
typedef struct _ParamSpecLexer ParamSpecLexer;

struct _Lexer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	LexerPrivate * priv;
};

struct _LexerClass {
	GTypeClass parent_class;
	void (*finalize) (Lexer *self);
};

struct _LexerPrivate {
	gchar* source;
	gint index;
	gint line;
};

struct _ParamSpecLexer {
	GParamSpec parent_instance;
};

static gint Lexer_private_offset;
static gpointer lexer_parent_class = NULL;

VALA_EXTERN gpointer lexer_ref (gpointer instance);
VALA_EXTERN void lexer_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_lexer (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags);
VALA_EXTERN void value_set_lexer (GValue* value,
                      gpointer v_object);
VALA_EXTERN void value_take_lexer (GValue* value,
                       gpointer v_object);
VALA_EXTERN gpointer value_get_lexer (const GValue* value);
VALA_EXTERN GType lexer_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Lexer, lexer_unref)
VALA_EXTERN Lexer* lexer_new (const gchar* source);
VALA_EXTERN Lexer* lexer_construct (GType object_type,
                        const gchar* source);
VALA_EXTERN gpointer token_ref (gpointer instance);
VALA_EXTERN void token_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_token (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags);
VALA_EXTERN void value_set_token (GValue* value,
                      gpointer v_object);
VALA_EXTERN void value_take_token (GValue* value,
                       gpointer v_object);
VALA_EXTERN gpointer value_get_token (const GValue* value);
VALA_EXTERN GType token_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Token, token_unref)
VALA_EXTERN Token* lexer_next_token (Lexer* self);
static void lexer_skip_whitespace (Lexer* self);
VALA_EXTERN GType token_type_get_type (void) G_GNUC_CONST ;
VALA_EXTERN Token* token_new (TokenType type,
                  const gchar* lexeme,
                  gint line);
VALA_EXTERN Token* token_construct (GType object_type,
                        TokenType type,
                        const gchar* lexeme,
                        gint line);
static gboolean lexer_isalpha (Lexer* self,
                        gchar c);
static Token* lexer_identifier_or_keyword (Lexer* self);
static gboolean lexer_isdigit (Lexer* self,
                        gchar c);
static Token* lexer_number (Lexer* self);
static Token* lexer_string_literal (Lexer* self);
static gboolean lexer_isalnum (Lexer* self,
                        gchar c);
static void lexer_finalize (Lexer * obj);
static GType lexer_get_type_once (void);

static inline gpointer
lexer_get_instance_private (Lexer* self)
{
	return G_STRUCT_MEMBER_P (self, Lexer_private_offset);
}

Lexer*
lexer_construct (GType object_type,
                 const gchar* source)
{
	Lexer* self = NULL;
	gchar* _tmp0_;
	g_return_val_if_fail (source != NULL, NULL);
	self = (Lexer*) g_type_create_instance (object_type);
	_tmp0_ = g_strdup (source);
	_g_free0 (self->priv->source);
	self->priv->source = _tmp0_;
	return self;
}

Lexer*
lexer_new (const gchar* source)
{
	return lexer_construct (TYPE_LEXER, source);
}

static gchar
string_get (const gchar* self,
            glong index)
{
	gchar _tmp0_;
	gchar result;
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = ((gchar*) self)[index];
	result = _tmp0_;
	return result;
}

Token*
lexer_next_token (Lexer* self)
{
	const gchar* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gchar current = '\0';
	const gchar* _tmp4_;
	gboolean _tmp5_ = FALSE;
	gint _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	Token* _tmp12_;
	Token* _tmp13_;
	Token* result;
	g_return_val_if_fail (self != NULL, NULL);
	lexer_skip_whitespace (self);
	_tmp0_ = self->priv->source;
	_tmp1_ = strlen (_tmp0_);
	_tmp2_ = _tmp1_;
	if (self->priv->index >= _tmp2_) {
		Token* _tmp3_;
		_tmp3_ = token_new (TOKEN_TYPE_END_OF_FILE, "", self->priv->line);
		result = _tmp3_;
		return result;
	}
	_tmp4_ = self->priv->source;
	current = string_get (_tmp4_, (glong) self->priv->index);
	if (lexer_isalpha (self, current)) {
		_tmp5_ = TRUE;
	} else {
		_tmp5_ = current == '_';
	}
	if (_tmp5_) {
		Token* _tmp6_;
		_tmp6_ = lexer_identifier_or_keyword (self);
		result = _tmp6_;
		return result;
	}
	if (lexer_isdigit (self, current)) {
		Token* _tmp7_;
		_tmp7_ = lexer_number (self);
		result = _tmp7_;
		return result;
	}
	if (current == '"') {
		Token* _tmp8_;
		_tmp8_ = lexer_string_literal (self);
		result = _tmp8_;
		return result;
	}
	_tmp9_ = self->priv->index;
	self->priv->index = _tmp9_ + 1;
	_tmp10_ = g_strdup_printf ("%c", current);
	_tmp11_ = _tmp10_;
	_tmp12_ = token_new (TOKEN_TYPE_SYMBOL, _tmp11_, self->priv->line);
	_tmp13_ = _tmp12_;
	_g_free0 (_tmp11_);
	result = _tmp13_;
	return result;
}

static void
lexer_skip_whitespace (Lexer* self)
{
	g_return_if_fail (self != NULL);
	while (TRUE) {
		gboolean _tmp0_ = FALSE;
		const gchar* _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		const gchar* _tmp9_;
		gint _tmp11_;
		_tmp1_ = self->priv->source;
		_tmp2_ = strlen (_tmp1_);
		_tmp3_ = _tmp2_;
		if (self->priv->index < _tmp3_) {
			gboolean _tmp4_ = FALSE;
			gboolean _tmp5_ = FALSE;
			const gchar* _tmp6_;
			_tmp6_ = self->priv->source;
			if (string_get (_tmp6_, (glong) self->priv->index) == ' ') {
				_tmp5_ = TRUE;
			} else {
				const gchar* _tmp7_;
				_tmp7_ = self->priv->source;
				_tmp5_ = string_get (_tmp7_, (glong) self->priv->index) == '\t';
			}
			if (_tmp5_) {
				_tmp4_ = TRUE;
			} else {
				const gchar* _tmp8_;
				_tmp8_ = self->priv->source;
				_tmp4_ = string_get (_tmp8_, (glong) self->priv->index) == '\n';
			}
			_tmp0_ = _tmp4_;
		} else {
			_tmp0_ = FALSE;
		}
		if (!_tmp0_) {
			break;
		}
		_tmp9_ = self->priv->source;
		if (string_get (_tmp9_, (glong) self->priv->index) == '\n') {
			gint _tmp10_;
			_tmp10_ = self->priv->line;
			self->priv->line = _tmp10_ + 1;
		}
		_tmp11_ = self->priv->index;
		self->priv->index = _tmp11_ + 1;
	}
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
	end = _tmp0_;
	_tmp1_ = end;
	if (_tmp1_ == NULL) {
		result = maxlen;
		return result;
	} else {
		gchar* _tmp2_;
		_tmp2_ = end;
		result = (glong) (_tmp2_ - str);
		return result;
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (offset >= ((glong) 0)) {
		_tmp0_ = len >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		string_length = string_strnlen ((gchar*) self, offset + len);
	} else {
		gint _tmp1_;
		gint _tmp2_;
		_tmp1_ = strlen (self);
		_tmp2_ = _tmp1_;
		string_length = (glong) _tmp2_;
	}
	if (offset < ((glong) 0)) {
		offset = string_length + offset;
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
	} else {
		g_return_val_if_fail (offset <= string_length, NULL);
	}
	if (len < ((glong) 0)) {
		len = string_length - offset;
	}
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
	result = _tmp3_;
	return result;
}

static Token*
lexer_identifier_or_keyword (Lexer* self)
{
	gint start = 0;
	gchar* lexeme = NULL;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	Token* _tmp10_;
	Token* result;
	g_return_val_if_fail (self != NULL, NULL);
	start = self->priv->index;
	while (TRUE) {
		gboolean _tmp0_ = FALSE;
		const gchar* _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		gint _tmp7_;
		_tmp1_ = self->priv->source;
		_tmp2_ = strlen (_tmp1_);
		_tmp3_ = _tmp2_;
		if (self->priv->index < _tmp3_) {
			gboolean _tmp4_ = FALSE;
			const gchar* _tmp5_;
			_tmp5_ = self->priv->source;
			if (lexer_isalnum (self, string_get (_tmp5_, (glong) self->priv->index))) {
				_tmp4_ = TRUE;
			} else {
				const gchar* _tmp6_;
				_tmp6_ = self->priv->source;
				_tmp4_ = string_get (_tmp6_, (glong) self->priv->index) == '_';
			}
			_tmp0_ = _tmp4_;
		} else {
			_tmp0_ = FALSE;
		}
		if (!_tmp0_) {
			break;
		}
		_tmp7_ = self->priv->index;
		self->priv->index = _tmp7_ + 1;
	}
	_tmp8_ = self->priv->source;
	_tmp9_ = string_substring (_tmp8_, (glong) start, (glong) (self->priv->index - start));
	lexeme = _tmp9_;
	_tmp10_ = token_new (TOKEN_TYPE_IDENTIFIER, lexeme, self->priv->line);
	result = _tmp10_;
	_g_free0 (lexeme);
	return result;
}

static Token*
lexer_number (Lexer* self)
{
	gint start = 0;
	gchar* lexeme = NULL;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	Token* _tmp8_;
	Token* result;
	g_return_val_if_fail (self != NULL, NULL);
	start = self->priv->index;
	while (TRUE) {
		gboolean _tmp0_ = FALSE;
		const gchar* _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		gint _tmp5_;
		_tmp1_ = self->priv->source;
		_tmp2_ = strlen (_tmp1_);
		_tmp3_ = _tmp2_;
		if (self->priv->index < _tmp3_) {
			const gchar* _tmp4_;
			_tmp4_ = self->priv->source;
			_tmp0_ = lexer_isdigit (self, string_get (_tmp4_, (glong) self->priv->index));
		} else {
			_tmp0_ = FALSE;
		}
		if (!_tmp0_) {
			break;
		}
		_tmp5_ = self->priv->index;
		self->priv->index = _tmp5_ + 1;
	}
	_tmp6_ = self->priv->source;
	_tmp7_ = string_substring (_tmp6_, (glong) start, (glong) (self->priv->index - start));
	lexeme = _tmp7_;
	_tmp8_ = token_new (TOKEN_TYPE_NUMBER, lexeme, self->priv->line);
	result = _tmp8_;
	_g_free0 (lexeme);
	return result;
}

static Token*
lexer_string_literal (Lexer* self)
{
	gint _tmp0_;
	gint start = 0;
	gchar* lexeme = NULL;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	gint _tmp9_;
	Token* _tmp10_;
	Token* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->index;
	self->priv->index = _tmp0_ + 1;
	start = self->priv->index;
	while (TRUE) {
		gboolean _tmp1_ = FALSE;
		const gchar* _tmp2_;
		gint _tmp3_;
		gint _tmp4_;
		gint _tmp6_;
		_tmp2_ = self->priv->source;
		_tmp3_ = strlen (_tmp2_);
		_tmp4_ = _tmp3_;
		if (self->priv->index < _tmp4_) {
			const gchar* _tmp5_;
			_tmp5_ = self->priv->source;
			_tmp1_ = string_get (_tmp5_, (glong) self->priv->index) != '"';
		} else {
			_tmp1_ = FALSE;
		}
		if (!_tmp1_) {
			break;
		}
		_tmp6_ = self->priv->index;
		self->priv->index = _tmp6_ + 1;
	}
	_tmp7_ = self->priv->source;
	_tmp8_ = string_substring (_tmp7_, (glong) start, (glong) (self->priv->index - start));
	lexeme = _tmp8_;
	_tmp9_ = self->priv->index;
	self->priv->index = _tmp9_ + 1;
	_tmp10_ = token_new (TOKEN_TYPE_STRING, lexeme, self->priv->line);
	result = _tmp10_;
	_g_free0 (lexeme);
	return result;
}

static gboolean
lexer_isalpha (Lexer* self,
               gchar c)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	if (c >= 'a') {
		_tmp1_ = c <= 'z';
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		gboolean _tmp2_ = FALSE;
		if (c >= 'A') {
			_tmp2_ = c <= 'Z';
		} else {
			_tmp2_ = FALSE;
		}
		_tmp0_ = _tmp2_;
	}
	result = _tmp0_;
	return result;
}

static gboolean
lexer_isdigit (Lexer* self,
               gchar c)
{
	gboolean _tmp0_ = FALSE;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	if (c >= '0') {
		_tmp0_ = c <= '9';
	} else {
		_tmp0_ = FALSE;
	}
	result = _tmp0_;
	return result;
}

static gboolean
lexer_isalnum (Lexer* self,
               gchar c)
{
	gboolean _tmp0_ = FALSE;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	if (lexer_isalpha (self, c)) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = lexer_isdigit (self, c);
	}
	result = _tmp0_;
	return result;
}

static void
value_lexer_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_lexer_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		lexer_unref (value->data[0].v_pointer);
	}
}

static void
value_lexer_copy_value (const GValue* src_value,
                        GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = lexer_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_lexer_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_lexer_collect_value (GValue* value,
                           guint n_collect_values,
                           GTypeCValue* collect_values,
                           guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		Lexer * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = lexer_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_lexer_lcopy_value (const GValue* value,
                         guint n_collect_values,
                         GTypeCValue* collect_values,
                         guint collect_flags)
{
	Lexer ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = lexer_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_lexer (const gchar* name,
                  const gchar* nick,
                  const gchar* blurb,
                  GType object_type,
                  GParamFlags flags)
{
	ParamSpecLexer* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_LEXER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_lexer (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LEXER), NULL);
	return value->data[0].v_pointer;
}

void
value_set_lexer (GValue* value,
                 gpointer v_object)
{
	Lexer * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LEXER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_LEXER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		lexer_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		lexer_unref (old);
	}
}

void
value_take_lexer (GValue* value,
                  gpointer v_object)
{
	Lexer * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LEXER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_LEXER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		lexer_unref (old);
	}
}

static void
lexer_class_init (LexerClass * klass,
                  gpointer klass_data)
{
	lexer_parent_class = g_type_class_peek_parent (klass);
	((LexerClass *) klass)->finalize = lexer_finalize;
	g_type_class_adjust_private_offset (klass, &Lexer_private_offset);
}

static void
lexer_instance_init (Lexer * self,
                     gpointer klass)
{
	self->priv = lexer_get_instance_private (self);
	self->priv->index = 0;
	self->priv->line = 1;
	self->ref_count = 1;
}

static void
lexer_finalize (Lexer * obj)
{
	Lexer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LEXER, Lexer);
	g_signal_handlers_destroy (self);
	_g_free0 (self->priv->source);
}

static GType
lexer_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_lexer_init, value_lexer_free_value, value_lexer_copy_value, value_lexer_peek_pointer, "p", value_lexer_collect_value, "p", value_lexer_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (LexerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lexer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Lexer), 0, (GInstanceInitFunc) lexer_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType lexer_type_id;
	lexer_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Lexer", &g_define_type_info, &g_define_type_fundamental_info, 0);
	Lexer_private_offset = g_type_add_instance_private (lexer_type_id, sizeof (LexerPrivate));
	return lexer_type_id;
}

GType
lexer_get_type (void)
{
	static volatile gsize lexer_type_id__once = 0;
	if (g_once_init_enter (&lexer_type_id__once)) {
		GType lexer_type_id;
		lexer_type_id = lexer_get_type_once ();
		g_once_init_leave (&lexer_type_id__once, lexer_type_id);
	}
	return lexer_type_id__once;
}

gpointer
lexer_ref (gpointer instance)
{
	Lexer * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
lexer_unref (gpointer instance)
{
	Lexer * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		LEXER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

