/* token.vala.c generated by valac 0.56.3, the Vala compiler
 * generated from token.vala, do not modify */

/* token.vala*/

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

typedef enum  {
	TOKEN_TYPE_IDENTIFIER,
	TOKEN_TYPE_KEYWORD,
	TOKEN_TYPE_NUMBER,
	TOKEN_TYPE_STRING,
	TOKEN_TYPE_SYMBOL,
	TOKEN_TYPE_END_OF_FILE,
	TOKEN_TYPE_UNKNOWN
} TokenType;

#define TYPE_TOKEN_TYPE (token_type_get_type ())

#define TYPE_TOKEN (token_get_type ())
#define TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TOKEN, Token))
#define TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TOKEN, TokenClass))
#define IS_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TOKEN))
#define IS_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TOKEN))
#define TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TOKEN, TokenClass))

typedef struct _Token Token;
typedef struct _TokenClass TokenClass;
typedef struct _TokenPrivate TokenPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ParamSpecToken ParamSpecToken;

struct _Token {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TokenPrivate * priv;
	TokenType type;
	gchar* lexeme;
	gint line;
};

struct _TokenClass {
	GTypeClass parent_class;
	void (*finalize) (Token *self);
};

struct _ParamSpecToken {
	GParamSpec parent_instance;
};

static gpointer token_parent_class = NULL;

VALA_EXTERN GType token_type_get_type (void) G_GNUC_CONST ;
VALA_EXTERN gpointer token_ref (gpointer instance);
VALA_EXTERN void token_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_token (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags);
VALA_EXTERN void value_set_token (GValue* value,
                      gpointer v_object);
VALA_EXTERN void value_take_token (GValue* value,
                       gpointer v_object);
VALA_EXTERN gpointer value_get_token (const GValue* value);
VALA_EXTERN GType token_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Token, token_unref)
VALA_EXTERN Token* token_new (TokenType type,
                  const gchar* lexeme,
                  gint line);
VALA_EXTERN Token* token_construct (GType object_type,
                        TokenType type,
                        const gchar* lexeme,
                        gint line);
VALA_EXTERN gchar* token_to_string (Token* self);
static void token_finalize (Token * obj);
static GType token_get_type_once (void);

static GType
token_type_get_type_once (void)
{
	static const GEnumValue values[] = {{TOKEN_TYPE_IDENTIFIER, "TOKEN_TYPE_IDENTIFIER", "identifier"}, {TOKEN_TYPE_KEYWORD, "TOKEN_TYPE_KEYWORD", "keyword"}, {TOKEN_TYPE_NUMBER, "TOKEN_TYPE_NUMBER", "number"}, {TOKEN_TYPE_STRING, "TOKEN_TYPE_STRING", "string"}, {TOKEN_TYPE_SYMBOL, "TOKEN_TYPE_SYMBOL", "symbol"}, {TOKEN_TYPE_END_OF_FILE, "TOKEN_TYPE_END_OF_FILE", "end-of-file"}, {TOKEN_TYPE_UNKNOWN, "TOKEN_TYPE_UNKNOWN", "unknown"}, {0, NULL, NULL}};
	GType token_type_type_id;
	token_type_type_id = g_enum_register_static ("TokenType", values);
	return token_type_type_id;
}

GType
token_type_get_type (void)
{
	static volatile gsize token_type_type_id__once = 0;
	if (g_once_init_enter (&token_type_type_id__once)) {
		GType token_type_type_id;
		token_type_type_id = token_type_get_type_once ();
		g_once_init_leave (&token_type_type_id__once, token_type_type_id);
	}
	return token_type_type_id__once;
}

Token*
token_construct (GType object_type,
                 TokenType type,
                 const gchar* lexeme,
                 gint line)
{
	Token* self = NULL;
	gchar* _tmp0_;
	g_return_val_if_fail (lexeme != NULL, NULL);
	self = (Token*) g_type_create_instance (object_type);
	self->type = type;
	_tmp0_ = g_strdup (lexeme);
	_g_free0 (self->lexeme);
	self->lexeme = _tmp0_;
	self->line = line;
	return self;
}

Token*
token_new (TokenType type,
           const gchar* lexeme,
           gint line)
{
	return token_construct (TYPE_TOKEN, type, lexeme, line);
}

gchar*
token_to_string (Token* self)
{
	GEnumValue* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_enum_get_value (g_type_class_ref (TYPE_TOKEN_TYPE), self->type);
	_tmp1_ = g_strconcat ("Token(", (_tmp0_ != NULL) ? _tmp0_->value_name : NULL, NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat (_tmp2_, ", '", NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = self->lexeme;
	_tmp6_ = g_strconcat (_tmp4_, _tmp5_, NULL);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strconcat (_tmp7_, "', line ", NULL);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strdup_printf ("%i", self->line);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp9_, _tmp11_, NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strconcat (_tmp13_, ")", NULL);
	_tmp15_ = _tmp14_;
	_g_free0 (_tmp13_);
	_g_free0 (_tmp11_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
	result = _tmp15_;
	return result;
}

static void
value_token_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_token_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		token_unref (value->data[0].v_pointer);
	}
}

static void
value_token_copy_value (const GValue* src_value,
                        GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = token_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_token_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_token_collect_value (GValue* value,
                           guint n_collect_values,
                           GTypeCValue* collect_values,
                           guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		Token * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = token_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_token_lcopy_value (const GValue* value,
                         guint n_collect_values,
                         GTypeCValue* collect_values,
                         guint collect_flags)
{
	Token ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = token_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_token (const gchar* name,
                  const gchar* nick,
                  const gchar* blurb,
                  GType object_type,
                  GParamFlags flags)
{
	ParamSpecToken* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_TOKEN), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_token (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TOKEN), NULL);
	return value->data[0].v_pointer;
}

void
value_set_token (GValue* value,
                 gpointer v_object)
{
	Token * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TOKEN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_TOKEN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		token_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		token_unref (old);
	}
}

void
value_take_token (GValue* value,
                  gpointer v_object)
{
	Token * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TOKEN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_TOKEN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		token_unref (old);
	}
}

static void
token_class_init (TokenClass * klass,
                  gpointer klass_data)
{
	token_parent_class = g_type_class_peek_parent (klass);
	((TokenClass *) klass)->finalize = token_finalize;
}

static void
token_instance_init (Token * self,
                     gpointer klass)
{
	self->ref_count = 1;
}

static void
token_finalize (Token * obj)
{
	Token * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TOKEN, Token);
	g_signal_handlers_destroy (self);
	_g_free0 (self->lexeme);
}

static GType
token_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_token_init, value_token_free_value, value_token_copy_value, value_token_peek_pointer, "p", value_token_collect_value, "p", value_token_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (TokenClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) token_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Token), 0, (GInstanceInitFunc) token_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType token_type_id;
	token_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Token", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return token_type_id;
}

GType
token_get_type (void)
{
	static volatile gsize token_type_id__once = 0;
	if (g_once_init_enter (&token_type_id__once)) {
		GType token_type_id;
		token_type_id = token_get_type_once ();
		g_once_init_leave (&token_type_id__once, token_type_id);
	}
	return token_type_id__once;
}

gpointer
token_ref (gpointer instance)
{
	Token * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
token_unref (gpointer instance)
{
	Token * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		TOKEN_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

